defaults:
  - optimizer: Adam

CIFAR10:
  _target_: torchvision.datasets.CIFAR10
  root: cifar10
  train: True
  download: True

DataLoader:
  _target_: torch.utils.data.DataLoader
  batch_size: 128
  num_workers: 2
  shuffle: True

Augmentations:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
    - _target_: torchvision.transforms.RandomHorizontalFlip

DiffusionModel:
  _target_: modeling.diffusion.DiffusionModel
  eps_model:
    _target_: modeling.unet.UnetModel
    in_channels: 3
    out_channels: 3
    hidden_size: 128
  betas:
    [1e-4, 0.02]
  num_timesteps: 100


name: main_config
n_gpu: 1
num_epochs: 100
logging_policy: 25
device: 'cpu'